name: 'Esbuild Run'
description: 'Runs esbuild'
inputs:
  fileDir:
    description: 'Function File Directory'
    required: true
    default: 'services/functions/src'
  moduleDir:
    description: 'Node Module Dir'
    required: true
    default: 'node_modules'
  outDir:
    description: 'Build Dir'
    required: true
    default: 'services/functions/lib'
outputs:
  file-list:
    description: 'The list of files to build'
  module_list:
    descriptoin: 'The module list'
  working-dir:
    description: 'The working directory'
runs:
  using: 'node16'
  main: 'index.js'