name: 'Esbuild Run'
description: 'Runs esbuild'
inputs:
  fileDir:
    description: 'Function File Directory'
    required: true
    default: 'services/functions/src'
  moduleDir:
    description: 'Node Module Dir'
    required: true
    default: 'node_modules'
  outDir:
    description: 'Build Dir'
    required: true
    default: 'services/functions/lib'
runs:
  using: 'node16'
  main: 'index.js'