name: 'Esbuild Run'
description: 'Runs esbuild'
runs:
  using: 'node16'
  inputs:
    fileDir:
      description: 'Function File Directory'
      required: true
      default: 'services/functions/src'
    moduleDir:
      description: 'Node Module Dir'
      required: true
      default: 'node_modules'
    outDir:
      description: 'Build Dir'
      required: true
      default: 'services/functions/lib'
  main: 'index.js'